<div class="footer-container">
  <div class="footer">
    <div class="right">
      <p>&copy; 2001–2013 2+3D Spółka z o.o.<br />
        <strong><?php echo $this->__('All rights reserved.');?></strong>
      </p>
      <ul class="creators">
        <li><?php echo $this->__('Project');?>: Wojtek Kubiena</li>
        <li><?php echo $this->__('Implementation');?>: nibynic</li>
        <li><?php echo $this->__('Logo');?>: Jacek Mrowczyk, Kuba Sowiński</li>
      </ul>
    </div>
  </div>
</div>
