<?php
/**
 * @var DpTD_Site_Block_Html_Footer $this
 */
?>
<?php $_helper = $this->helper('site');?>
<div class="footer-container">
  <div class="footer">
    <div class="left">
      <ul id="footerMenu" class="menu">
        <?php foreach ($this->getFooterMenu() as $data):?>
          <?php $mItem = $data['element'];$smItems = isset($data['sublevel']) ? $data['sublevel'] : null;?>
          <li id="menuItem_<?php $mItem->getId();?>" class="menuItem">
            <h3>
              <?php if ($url = $_helper->menuItemUrl(array('item' => $mItem))):?>
                <a class="link" href="<?php echo $url;?>"><?php echo $mItem->getTitle();?></a>
              <?php else:?>
                <?php echo $mItem->getTitle();?>
              <?php endif;?>
            </h3>
            <?php if (count($smItems) > 0):?>            
              <?php echo $this->getLayout()->getBlock('site.children')->setCollection($smItems)->setMenuItem($mItem)->toHtml();?>            
            <?php endif;?>            
          </li>
        <?php endforeach;?>
      </ul>
    </div>
    <div class="copyrights">
      <p>
        © 2001-2012 2+3D Spółka z o.o.<br/>
        Wszelkie prawa zastrzeżone.
      </p>
      <p>
        Projekt: Wojtek Kubiena<br/>
        Wykonanie: <a href="http://nibynic.com/">nibynic</a><br/>
        Logo: Jacek Mrowczyk, Kuba Sowiński
      </p>
    </div>
  </div>
</div>
