<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<div class="nav-container">
<ul id="menu">
  <li class="menuItem first">
    <a href="http://2plus3d.pl/artykuly">Artykuły</a>
  </li>
  <li class="menuItem">
    <a href="http://2plus3d.pl/kalendarium">Kalendarium</a>
  </li>
  <li class="menuItem">
    <a href="http://2plus3d.pl/o-kwartalniku">Kwartalnik</a>
  </li>
  <li class="menuItem current">
    <a href="http://sklep.2plus3d.pl">Księgarnia</a>
  </li>
</ul>
</div>