<?php
/**
 * Top menu for store
 *
 * @see DpTD_Menu_Block_Html_Topmenu
 * @var $this DpTD_Menu_Block_Html_Topmenu
 * @var $_helper DpTD_Site_Helper_Data
 */
?>
<?php $_helper = $this->helper('site');?>
<?php $menu = $this->getMainMenu();?>
<div class="nav-container">
  <ul id="menu">
    <?php foreach($menu as $position => $items):?>
    <?php $mItem = $items['element']; $smItems = isset($items['sublevel']) ? $items['sublevel'] : null;?>
    <li class="menuItem <?php if ($mItem->getLiClass()): echo $mItem->getLiClass(); endif;?>">
      <?php $elem_url = $mItem->getAdditional() == true ? $mItem->getLink() : $_helper->menuItemUrl(array('item' => $mItem));?>
      <a href="<?php echo $elem_url;?>" class="link"><?php echo $this->__($mItem->getTitle());?></a>
      <?php if ((count($smItems) > 0) || $mItem->getPreview() != null):?>
      <a href="#" class="submenuToggler slideButton" id="submenuToggler_13"></a>
      <?php endif;?>
      <?php if (array_key_exists('submenuBlock', $items)):?>
        <div class="submenuBlock">
          <?php if (is_object($items['submenuBlock'])):?>
          <?php echo $items['submenuBlock']->toHtml();?>
          <?php else: ?>
          <?php echo $this->getChildHtml($items['submenuBlock']);?>
          <?php endif;?>
        </div>
      <?php endif;?>
    </li>
    <?php endforeach;?>
  </ul>
</div>
<div class="submenu-container" id="submenu">
<?php foreach($menu as $position => $items):?>
  <?php $mItem = $items['element']; $smItems = isset($items['sublevel']) ? $items['sublevel'] : null;?>
  <?php if ((count($smItems) > 0) || $mItem->getPreview() != null):?>
    <div id="submenu_<?php echo $mItem->getId(); ?>" class="<?php echo $mItem->getType();?>Submenu submenu slideDescription" style="display: none;">
      <div class="submenu-wrapper">
        <div class="spacer"></div>
        <?php if (count($smItems) > 0):?>
          <?php echo $this->getLayout()->getBlock('site.children')->setCollection($smItems)->setMenuItem($mItem)->toHtml();?>
        <?php endif;?>
        <?php if ($mItem->getPreview() != null):?>
          <?php echo $this->getLayout()->createBlock("site/preview_{$mItem->getPreview()}")->setMenuItem($mItem)->toHtml();?>
        <?php endif;?>
      </div>
    </div>
    <div class="slidePhoto" style="display:none"></div>
  <?php endif;?>
<?php endforeach;?>
</div>

<script type="text/javascript" charset="utf-8">
  
  document.observe('dom:loaded', function() {
    var submenu = new Nibynic.Slides('submenu', 'submenu', 'menu', { 
      interval: 0,
      duration: 0.5,
      queueEffects: true,
      autoStart: false,
      allowDeselect: true,
      rememberLocation: true,
      hashParamName: 'submenu',
      effects: {
        photoInEffect: {
          from: null,
          to: null
        },
        photoOutEffect: {
          from: null,
          to: null
        },
        descriptionInEffect: Effect.SlideDown,
        descriptionOutEffect: Effect.SlideUp
      }
    });
    var selectedSubmenuIndex = Nibynic.LocationHash.getParam('submenu');
    if(selectedSubmenuIndex) {  
      submenu.selectSlide(selectedSubmenuIndex, true);
    }
  });
</script>
