<?php if ($this->isPossibleOnepageCheckout()):?>
<?php $buttonText = $this->getButtonText() != null ? $this->getButtonText() : 'To Checkout';?>
<button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"><span><span><?php echo $this->__($buttonText) ?></span></span></button>
<?php endif?>
