<?php
/**
* Category siebar block
*
*/
/** @var $this DpTD_Catalog_Block_Category_Block */
?>
<div class="block block-category">
  <div class="block-title">
    <a href="<?php echo $this->getCategory()->getUrl();?>">
      <strong><span><?php echo $this->__($this->getCategory()->getName()) ?></span></strong>
    </a>
  </div>
  <div class="block-content">
    <ul class="links products-links">
    <?php foreach($this->getProductsCollection() as $_product):?>
      <li>
        <a href="<?php echo $_product->setCategoryId($this->getCategory()->getId())->getProductUrl();?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>, 
        <?php $_priceIncludingTax = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice(), true);?>
        <?php $_basepriceIncludingTax = $this->helper('tax')->getPrice($_product, $_product->getPrice(), true);?>
        <?php if ($_priceIncludingTax < $_basepriceIncludingTax):?>
        <span class="old-price">
          <span class="price"><?php echo Mage::helper('core')->currency($_basepriceIncludingTax,true,false);?></span>
        </span>
        <span class="special-price">
          <span class="price"><?php echo Mage::helper('core')->currency($_priceIncludingTax,true,false);?></span>
        </span>
        <?php else:?>
        <span class="price"><?php echo Mage::helper('core')->currency($_basepriceIncludingTax,true,false);?></span>
        <?php endif;?>
      </li>
    <?php endforeach;?>
    </ul>
  </div>
</div>