<?php
/** @var Mage_Checkout_Block_Onepage_Billing $this */
?>
<form id="co-billing-form" action="" autocomplete="on">
<fieldset>
  <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
    <li class="wide">
      <label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
      <div class="input-box">
        <?php echo $this->getAddressesHtmlSelect('billing') ?>
      </div>
    </li>
    <?php endif; ?>
    <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
      <fieldset>
        <legend><?php echo $this->__('Contact Information');?></legend>
        <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
        <ul>
          <li class="field"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?></li>
          <li class="fields">
            <?php if(!$this->isCustomerLoggedIn()): ?>
            <div class="field">
              <label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?>:</label>
              <div class="input-box">
                <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
              </div>
            </div>
            <?php endif; ?>
            <div class="field">
              <label for="billing:telephone"><?php echo $this->__('Telephone') ?>:</label>
              <div class="input-box">
                <input type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" />
              </div>
            </div>          
          </li>
        </ul>
      </fieldset>
      <fieldset>
        <legend><?php echo $this->__('Billing Address');?></legend>
        <ul>
          <li class="fields">
            <div class="field">
              <label for="billing:company"><?php echo $this->__('Company') ?>:</label>
              <div class="input-box">
                <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
              </div>
            </div>
          </li>
          <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
          <li class="wide">            
            <label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Street') ?>:</label>
            <div class="input-box">
              <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
            </div>
          </li>
          <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
          <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
          <li class="wide">
            <div class="input-box">
              <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
            </div>
          </li>
          <?php endfor; ?>
          
          <li class="fields">
            <div class="field">
              <label for="billing:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?>:</label>
              <div class="input-box">
                <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
              </div>
            </div>
            <div class="field">
              <label for="billing:city" class="required"><em>*</em><?php echo $this->__('City') ?>:</label>
              <div class="input-box">
                <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="billing:city" />
              </div>
            </div>
            
          </li>
              
          <li class="fields">
            <div class="field">
              <label for="billing:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?>:</label>
              <div class="input-box">
                <?php echo $this->getCountryHtmlSelect('billing') ?>
              </div>
              <p class="restriction"><?php echo $this->__('Currently we only accept orders from Poland');?></p>
            </div>
          </li>
          
          <li class="control">
            <input type="checkbox" name="billing[require_invoice]" id="billing:require_invoice" value="1" title="<?php echo  $this->__('Require Invoice') ?>" onclick="billing.toggleInvoiceFields(this)" class="checkbox" /><label for="billing:require_invoice"><?php echo  $this->__('I want to receive the invoice') ?></label>
          </li>
          
          <li class="fields" id="invoice-fields">            
            <div class="field">
              <label for="billing:vat_id" class="uppercase"><?php echo $this->__('TAX/VAT Number') ?>:</label>
              <div class="input-box">
                <input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text validate-nip <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
              </div>
            </div>
          </li>
          <?php if ($this->canShip()): ?>
          <li class="control shipping_address_settings <?php if ($this->customerHasAddresses()): ?>no-indent<?php endif;?>">
            <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" checked="checked" title="<?php echo  $this->__('Ship to this address') ?>" onclick="$('shipping:same_as_billing').checked = true;" class="radio" /><label for="billing:use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label></li>
          <li class="control shipping_address_settings <?php if ($this->customerHasAddresses()): ?>no-indent<?php endif;?>">
            <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0" title="<?php echo $this->__('Ship to different address') ?>" onclick="$('shipping:same_as_billing').checked = false;" class="radio" /><label for="billing:use_for_shipping_no"><?php echo $this->__('Ship to different address') ?></label>
          </li>
          <?php endif; ?>
          
          <?php if(!$this->isCustomerLoggedIn()): ?>
          <li class="fields" id="register-customer-password">
            <div class="field">
              <label for="billing:customer_password" class="required"><em>*</em><?php echo $this->__('Password') ?>:</label>
              <div class="input-box">
                <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
              </div>
            </div>
            <div class="field">
              <label for="billing:confirm_password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?>:</label>
              <div class="input-box">
                <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
              </div>
            </div>
          </li>            
          <?php endif; ?>
          
          <?php echo $this->getChildHtml('form.additional.info'); ?>
        </ul>
      </fieldset>  
      <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
    </li>
  </ul>
  
  <?php if (!$this->canShip()): ?>
  <input type="hidden" name="billing[use_for_shipping]" value="1" />
  <?php endif; ?>
  
  <div class="buttons-set" id="billing-buttons-container">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="billing.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
    <span class="please-wait" id="billing-please-wait" style="display:none;">
      <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
  </div>
</fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
  var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
  var billingForm = new VarienForm('co-billing-form');
  billing.toggleInvoiceFields($('billing:require_invoice'))
  if ($('onepage-guest-register-button')) {
    Event.observe($('onepage-guest-register-button'), 'click', function(event) {
      var billingRememberMe = $('co-billing-form').select('#remember-me-box');
      if (billingRememberMe.length > 0) {
        if ($('login:guest') && $('login:guest').checked) {
          billingRememberMe[0].hide();
        } else if ($('login:register') && ($('login:register').checked || $('login:register').type == 'hidden')) {
          billingRememberMe[0].show();
        }
      }
    });
  }
//]]>
</script>
