<div class="step-block step-register" id="simplecheckout-register-form" style="display: none;">
  <div class="close-btn" onclick="link.hide();">x</div>
  <div class="step-frame">
    <h2>
      <span>
        <?php echo $this->__($this->getStepTitle()); ?>
      </span>
    </h2>
    <hr clas="ruler" />
    <div class="step-form">
      <form action="<?php echo $this->getRegisterPostActionUrl() ?>" method="post" id="register-form">
        <ul class="form-list">
          <li class="fields">
            <?php //echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
          </li>
          <li>
            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
            <div class="input-box">
              <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
            </div>
          </li>
          <li class="fields">
            <div class="field">
              <label for="customer_password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
              <div class="input-box">
                <input type="password" name="customer_password" id="customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
              </div>
            </div>
            <div class="field">
              <label for="confirm_password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
              <div class="input-box">
                <input type="password" name="confirm_password" title="<?php echo $this->__('Confirm Password') ?>" id="confirm_password" class="input-text required-entry validate-cpassword" />
              </div>
            </div>
          </li>
          <li class="center buttons-set">
            <button type="button" onclick="link.register();return false;" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
          </li>
          
          <?php if ($this->isNewsletterEnabled()): ?>
          <li class="control">
            <div class="input-box">
              <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if ($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
              <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
            </div>            
          </li>
          <?php endif ?>
        </ul>
      </form>
    </div>
  </div>
  <hr clas="ruler" />
  <div class="step-footer">
      <img src="<?php echo $this->getSkinUrl('images/simplecheckout/secure.png'); ?>" />
      <span><?php echo $this->__('Checking out on %s is safe and secure', $this->getStoreName()); ?></span>
  </div>
</div>