<tr>
  <td colspan="3" class="a-right"><?php echo $this->__('Subtotal');?>:</td>
  <td class="a-center">
    <?php echo $this->helper('core')->currency($this->getSubtotal()->getValue());?>
  </td>
</tr>
<tr class="last">
  <td colspan="3" class="a-right"><?php echo $this->__('If Shipping');?>:</td>
  <td class="a-center">
    <?php echo $this->helper('core')->currency($this->getShippingTotal()->getValue());?>
  </td>
</tr>
<tr class="grandtotal">
  <td colspan="3" class="a-right"><?php echo $this->__('Total');?>:</td>
  <td class="a-center">
  <?php  if ($this->helper('simplecheckout')->showGrandTotalWithTax()):?>
    <?php echo $this->helper('core')->currency($this->getGrandTotal()->getValue());?>
  <?php else: ?>
    <?php echo $this->helper('core')->currency($this->getGrandTotalExcludingTax());?>
  <?php endif; ?>
  </td>
</tr>

