<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $_product->isSaleable() ? $this->__('To Cart') : $this->__('Sold Out'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <input type="hidden" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <?php endif; ?>
        <?php echo $this->getPriceHtml($_product);?>
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <span class="shipping-cost-info"><?php echo $this->__('Price includes the shipping cost and tax');?></span>
        <span class="shipping-cost-info">
          <?php echo $this->__('The parcel is protected with cardboard box');?><br />
          <a href="<?php echo $this->getUrl('platnosc-i-dostawa');?>"><?php echo $this->__('See');?></a>
        </span>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php else :?>
<div class="add-to-cart">
  <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart btn-cart-sold-out"><span><span><?php echo $buttonTitle ?></span></span></button>
</div>
<?php endif; ?>
