<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('To Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <input type="hidden" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <?php endif; ?>
        <?php echo $this->getPriceHtml($_product);?>
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <span class="shipping-cost-info"><?php echo $this->__('price includes the shipping cost and tax');?></span>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
