<div id="billing-address-changer" <?php if($this->helper('simplecheckout')->isBillingSameAsShipping()): ?> style="display:none;"<?php endif; ?>> 
  <h3>
    <span><?php echo $this->__('Please Enter Billing Information');?></span>
  </h3>
  <?php if ($this->customerHasAddresses()): ?>
  <input type="hidden" name="selected_billing_address_id" value="<?php echo $this->getSelectedBillingAddressId()?>" />
  <div class="input-box">
    <?php echo $this->getAddressesHtmlSelect('billing') ?>
  </div>
  <?php endif ?>
  
  <div id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
    <fieldset>
      <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />

      <div class="box-float">        
        <div class="field">
          <div class="input-box">
            <input type="text" title="<?php echo $this->__('First Name') ?>" placeholder="<?php echo $this->__('FIRST NAME') ?>" name="billing[firstname]" id="billing:firstname" value="<?php echo $this->escapeHtml($this->getAddress()->getFirstname()) ?>" class="input-text required-entry" />
          </div>
        </div>
        <div class="field">
          <div class="input-box">
            <input type="text" title="<?php echo $this->__('Last Name') ?>" placeholder="<?php echo $this->__('LAST NAME') ?>" name="billing[lastname]" id="billing:lastname" value="<?php echo $this->escapeHtml($this->getAddress()->getLastname()) ?>" class="input-text required-entry"  />
          </div>
        </div>        
      </div>

      <div class="box-wide">
        <div class="row">
          <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
          <div class="input-box">
            <input type="text" title="<?php echo $this->__('Street Address') ?>" placeholder="<?php echo $this->__('ADDRESS LINE 1');?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" />
          </div>
        </div>

        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>                    
        <div class="row">
          <div class="input-box">
            <input type="text" title="<?php echo $this->__('Address Line %s', $_i) ?>" placeholder="<?php echo $this->__('ADDRESS LINE %s (optional)', $_i);?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
          </div>
        </div>
        <?php endfor; ?>     

        <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
        <div class="row">
          <div class="input-box">
            <input type="text" id="billing:vat_id" name="billing[vat_id]" placeholder="<?php echo $this->__('VAT Number'); ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
          </div>
        </div>
        <?php endif; ?>
      </div>
      <div class="box-float">
        <div class="field city-field">
          <div class="input-box">
            <input type="text" placeholder="<?php echo $this->__('CITY') ?>" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="billing:city" onchange="billing.setSameAsBilling(false);" />
          </div>
        </div>
        <div class="field state-field">
          <div class="input-box">
            <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
              <option value=""><?php echo $this->__('State') ?></option>
            </select>
            <script type="text/javascript">
            //<![CDATA[
                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
            //]]>
            </script>
            <input type="text" id="billing:region" placeholder="<?php echo $this->__('Region');?>" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
          </div>
        </div>
        <div class="field zip-field">
          <div class="input-box">
            <input type="text" placeholder="<?php echo $this->__('ZIP');?>" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
          </div>
        </div>
      </div>

      <div class="box-float">
        <div class="field">
          <div class="input-box">
            <?php echo $this->getCountryHtmlSelect('billing') ?>
          </div>
        </div>
        <div class="field">
          <div class="input-box">
            <input type="hidden" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" id="billing:telephone" />
          </div>
        </div>
      </div>
    </fieldset>  
  </div>
</div>
<script type="text/javascript">
//<![CDATA[
    window.billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
//]]>
</script>