<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<div class="account-login">
  <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
  <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
    <div class="registered-users">
      <div class="content">
        <h2><?php echo $this->__('Log In') ?></h2>
        <ul class="form-list">
          <li>
            <label for="email" class="required"><?php echo $this->__('Email') ?>:</label>
            <div class="input-box">
              <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
            </div>
          </li>
          <li>
            <label for="pass" class="required"><?php echo $this->__('Password') ?>:</label>
            <div class="input-box">
              <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
            </div>
          </li>
          <?php echo $this->getChildHtml('form.additional.info'); ?>
          <?php echo $this->getChildHtml('persistent.remember.me'); ?>
        </ul>
        <div class="buttons-set">
          <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Log In') ?></span></span></button>
          <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="password-forgot"><?php echo $this->__('Forgot Your Password?') ?></a>
        </div>
      </div>
    </div>    
  </form>
  <script type="text/javascript">
  //<![CDATA[
    var loginDataForm = new VarienForm('login-form', true);
  //]]>
  </script>
</div>
<div class="new-users">
  <div class="content">
    <?php echo $this->getChildHtml('customer_login_form_register');?>
  </div>
</div>
<?php if (Mage::helper('checkout')->isContextCheckout()): ?>
  <input name="context" type="hidden" value="checkout" />
<?php endif; ?>