<?php
/**
* Homepage product list template
*
* @see DpTD_Category_Block_Listing
*/
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
  <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>  
  <ol class="products-collection products-list">
    <?php $_product = $_productCollection->getFirstItem();?>
    <!--FIRST PRODUCT -->
    <li class="item">
      <div class="left">
        <?php // Product Image ?>
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" class="product-image">
          <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(195); ?>" width="195" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
        </a>
        <div class="add-to-box">
          <?php echo  $this->getAddToCartHtml($_product);?>
        </div>
      </div>
      
      <div class="right">        
          <p class="category">
            <a href="<?php echo $this->helper('catalog')->getProductCategoryLink($_product);?>"><?php echo $this->helper('catalog')->getProductCategoryName($_product);?></a>
          </p>
        
        <div class="product-name">
          <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
          <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
            <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
          </a>
        </div>
        <div class="product-info">
        <?php if ($_product->getShortDescription()):?>
          <div class="description">
            <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
          </div>
        <?php endif;?>
        </div>
      </div>
    </li>
  </ol>
  <?php if ($_productCollection->count() > 1):?>
  <!-- REST OF THE PRODUCTS -->
  <ol class="products-collection products-grid">
  <?php $_iterator = 0; ?>
  <?php foreach ($_productCollection as $_product): ?>
  
    <?php if( $_iterator > 0 ): ?> 
    
    <li class="item">
      <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" class="product-image">
        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(195); ?>" width="195" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
      </a>

      <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
      <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>" class="product-name">
        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
      </a>
      <div class="add-to-box">
        <?php echo  $this->getAddToCartHtml($_product);?>
      </div>
    </li>
    
    <?php endif; ?>
    
    
  <?php $_iterator++;endforeach;?>
  </ol>
  <?php endif;?>
<?php endif;?>
