<?php
/**
* Homepage product list template
*
* @see DpTD_Category_Block_Listing
*/
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
  <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>  
  <ol class="products-list" id="products-list">
  
  <?php $_iterator = 0; ?>
  <?php foreach ($_productCollection as $_product): ?>
  
    <?php if( $_iterator == 0 ): ?> <!--FIRST PRODUCT -->
    <li class="item first<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
      <div class="left">
        <?php // Product Image ?>
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(193,263); ?>" width="193" height="263" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" /></a>
        <div class="add-to-box">
          <?php echo  $this->getAddToCartHtml($_product);?>
        </div>
      </div>
      
      <div class="right">
        <?php if ($_iterator == 1):?>
          <p class="category">
            <?php echo $this->helper('catalog')->getProductCategoryName($_product);?>
          </p>          
        <?php endif?>
        
        <div class="product-name">
          <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
          <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
            <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
          </a>
        </div>
        <?php if ($_product->getShortDescription()):?>
          <div class="description">
            <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
          </div>
        <?php endif;?>
      </div>
    </li>
    <?php else:?><!-- REST OF THE PRODUCTS -->
    
    <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
      <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(193,263); ?>" width="193" height="263" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" /></a>

      <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
      <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
      </a>
      
      <?php echo  $this->getAddToCartHtml($_product);?>
    </li>
    
    <?php endif; ?>
    
    
  <?php endforeach;?>
  </ol>
<?php endif;?>
