<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
      <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
        
        <?php // Product Name ?>
        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <?php $author = $_product->getAuthor() != null ? $_product->getAuthor() : $_product->getRedactor();  ?>
        <h2 class="product-name">
          <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
            <span class="author"><?php echo $author ?></span>, <span class="title"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>          
          </a>
        </h2>

        <?php // Product Image ?>
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(180,290); ?>" width="180" height="290" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>

        <?php // Product description ?>
        <div class="product-info">
          <div class="f-fix">
            
            <?php if($_product->getRatingSummary()): ?>
            <?php echo $this->getReviewsSummaryHtml($_product) ?>
            <?php endif; ?>

            <div class="desc std">
              <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
              <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('More...') ?></a>
            </div>

            <?php echo $this->getPriceHtml($_product, true) ?>

            <?php if($_product->isSaleable()): ?>
            <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
            <?php else: ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
            
          </div>
        </div>
      </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
    
    <?php else: ?>

    <?php // Grid Mode ?>

    
    <?php endif; ?>
</div>
<?php endif; ?>
