<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_mode = $this->getForceMode() ? $this->getForceMode() : $this->getMode();
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($_mode !='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-collection products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
      <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
        
        <?php // Product Image ?>
        <div class="left">
          <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(195); ?>" width="195" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
          </a>
          
          <?php // Add to cart button?>
          <div class="add-to-box">
            <div class="add-to-cart">
              <?php $buttonTitle = $_product->isSaleable() ? $this->__('Buy') : $this->__('Sold Out'); ?>
              <?php if($_product->isSaleable()): ?>
                <?php if(!$_product->isGrouped()): ?>
                <input type="hidden" name="qty" id="qty" maxlength="1" value="1" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <a title="<?php echo $buttonTitle ?>" class="button btn-cart" href="<?php echo $this->getAddToCartUrl($_product) ?>"><span><span><?php echo $buttonTitle ?></span></span></a>
                
              <?php else: ?>
              <a title="<?php echo $buttonTitle ?>" class="button btn-cart btn-cart-sold-out"><span><span><?php echo $buttonTitle ?></span></span></a>
              <?php endif; ?>
            </div>
          </div>
        </div>

        <div class="right">
          <?php // Product Name ?>
          <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
          <?php $author = $_product->getAuthor() != null ? $_product->getAuthor() : $_product->getRedactor();  ?>
          <h2 class="product-name">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
              <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
            </a>
          </h2>
          <?php // Product description ?>
          <div class="product-info">            
              <?php if($_product->getRatingSummary()): ?>
              <?php echo $this->getReviewsSummaryHtml($_product) ?>
              <?php endif; ?>
              <div class="description std">
                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?> (...)
              </div>
          </div>
        </div>
      </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
    
    <?php else: ?>

    <?php // Grid Mode ?>
    <ol class="products-collection products-grid">
      <?php foreach ($_productCollection as $_product): ?>
      <li class="item">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" class="product-image">
          <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(195); ?>" width="195" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
        </a>

        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>" class="product-name">
          <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
        </a>
        <?php if ($this->getShowPublishDate()):?>
        <p class="publish-date">
          <?php echo $_product->getPublishDate();?>
        </p>
        <?php endif;?>
        <?php // Add to cart button?>
          <div class="add-to-box">
            <div class="add-to-cart">
              <?php $buttonTitle = $_product->isSaleable() ? $this->__('Buy') : $this->__('Sold Out'); ?>
              <?php if($_product->isSaleable()): ?>
                <?php if(!$_product->isGrouped()): ?>
                <input type="hidden" name="qty" id="qty" maxlength="1" value="1" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <a title="<?php echo $buttonTitle ?>" class="button btn-cart" href="<?php echo $this->getAddToCartUrl($_product) ?>"><span><span><?php echo $buttonTitle ?></span></span></a>
                
              <?php else: ?>
              <a title="<?php echo $buttonTitle ?>" class="button btn-cart btn-cart-sold-out"><span><span><?php echo $buttonTitle ?></span></span></a>
              <?php endif; ?>
            </div>
          </div>
      </li>
      <?php endforeach;?>  
    </ol>    
    
    <?php endif; ?>
</div>
<?php endif; ?>
