<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
  <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
      <div class="no-display">
        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
      </div>

      <div class="product-shop">
          <p class="category">
            <a href="<?php echo $this->helper('catalog')->getProductCategoryLink($_product);?>"><?php echo $this->helper('catalog')->getProductCategoryName($_product);?></a>
          </p>
          <div class="product-name">
            <h1>
              <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
              <?php if ($_product->getAuthor() != null):?>
              <p class="author"><span class="caps"><?php echo $_product->getAuthor();?></span></p>
              <?php elseif ($_product->getRedactor() != null): ?>
              <p class="author"><span class="caps"><?php echo $_product->getRedactor();?></span> (<?php echo $this->__('ed.');?>)</p>
              <?php endif;?>              
            </h1>
          </div>
          <?php if ($_product->getDescription()):?>
            <div class="description">
              <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?></div>
            </div>
          <?php endif;?>
          <?php echo $this->getChildHtml('product_photos');?>
      </div>

      <div class="product-img-box">
        <?php echo $this->getChildHtml('media') ?>
        <?php echo $this->getChildHtml('product.book.info') ?>
        <?php echo $this->getChildHtml('product_type_data') ?>
        <?php if (!$this->hasOptions()):?>
          <div class="add-to-box">
            <?php echo $this->getChildHtml('addtocart') ?>
          </div>
        <?php endif; ?>
      </div>

      <div class="clearer"></div>
      <?php if ($_product->isSaleable() && $this->hasOptions()):?>
        <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
      <?php endif;?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
      var productAddToCartForm = new VarienForm('product_addtocart_form');
      productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
          var form = this.form;
          var oldUrl = form.action;

          if (url) {
            form.action = url;
          }
          var e = null;
          try {
            this.form.submit();
          } catch (e) {
          }
          this.form.action = oldUrl;
          if (e) {
            throw e;
          }

          if (button && button != 'undefined') {
            button.disabled = true;
          }
        }
      }.bind(productAddToCartForm);

      productAddToCartForm.submitLight = function(button, url){
        if(this.validator) {
          var nv = Validation.methods;
          delete Validation.methods['required-entry'];
          delete Validation.methods['validate-one-required'];
          delete Validation.methods['validate-one-required-by-name'];
          // Remove custom datetime validators
          for (var methodName in Validation.methods) {
            if (methodName.match(/^validate-datetime-.*/i)) {
              delete Validation.methods[methodName];
            }
          }

          if (this.validator.validate()) {
            if (url) {
              this.form.action = url;
            }
            this.form.submit();
          }
          Object.extend(Validation.methods, nv);
        }
      }.bind(productAddToCartForm);
    //]]>
    </script>
  </div>  
</div>
