<?php
/**
 * @var $this Mage_Tax_Block_Checkout_Grandtotal
 * @see Mage_Tax_Block_Checkout_Grandtotal
 */
?>
<?php if ($this->includeTax() && $this->getTotalExclTax()>=0):?>
<tr class="totals-grand totals-grand-excl">
    <td class="no-border"></td>
    <td style="<?php echo $this->getStyle() ?>" class="a-left">
        <strong><?php echo $this->helper('tax')->__('Total to Pay Excl. Tax')?></strong>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="2">
        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotalExclTax()) ?></strong>
    </td>
</tr>
<?php echo $this->renderTotals('taxes', $this->getColspan()); ?>
<tr class="totals-grand totals-grand-incl">
    <td class="no-border"></td>
    <td style="<?php echo $this->getStyle() ?>" class="a-left">
        <strong><?php echo $this->helper('tax')->__('Total to Pay Incl. Tax')?></strong>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="2">
        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
    </td>
</tr>
<?php else:?>
<tr class="totals-grand">
    <td class="no-border"></td>
    <td style="<?php echo $this->getStyle() ?>" class="a-left">
        <strong><?php echo $this->__('Total to Pay') ?></strong>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right total-cost" colspan="2">
        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
    </td>
</tr>
<?php endif;?>
