<div class="checkout-container">
  <ul class="steps">
    <?php foreach($this->getSteps() as $stepCode => $stepBlockName):?>
    <li class="step-<?php echo $stepCode;?>" id="step-<?php echo $stepCode;?>">
      <div class="step-frame-wrapper">
        <div class="step-frame">
          <h2>
            <span>
              <?php echo $this->__($this->getStepTitle($stepCode)); ?>
              <span class="step-edit" onclick="checkout.returnToStep('<?php echo $stepCode;?>');">
                <?php echo $this->__('Edit');?>
              </span>
            </span>
          </h2>
          <div class="step-form">
            <?php echo $this->getChildHtml($stepBlockName); ?>
          </div>
        </div>
      </div>
      <div class="next-steps">
        <?php foreach($this->getNextSteps($stepCode) as $caption => $stepName):?>
        <p><?php echo $this->__($caption);?>: <?php echo $stepName;?></p>
        <?php endforeach;?>
      </div>
    </li>
    <?php endforeach; ?>
  </ul>
  
  <div id="loader-container" class="loader-container" style="display: none;">
    <div class="ajax-loader" id="ajax-loader">
      <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif');?>" />
      <p><?php echo $this->__('Saving step. Please wait...');?></p>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var checkout = new SimpleCheckout('<?php echo $this->getCurrentStep()?>', '<?php echo $this->getReturnUrl()?>', '<?php echo $this->helper('simplecheckout')->getCheckoutType()?>');
//]]>
</script>
</div>