<?php if ($this->isSimpleCheckoutPossible()):?>
  <div id="simplecheckout-link-container">
    <button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="link.gotoCheckout();"><span><span><?php echo $this->__('Go to Simplecheckout') ?></span></span></button>
  </div>
  <script type="text/javascript">
  //<![CDATA[
    var link = new SimpleCheckoutLink('<?php echo $this->getCheckoutUrl() ?>', '<?php echo $this->getLoginUrl() ?>', <?php echo (int)$this->helper('simplecheckout')->isCustomerLoggedIn(); ?>);  
  //]]>
  </script>  
<?php endif;?>
 