<div id="checkout-review-table-wrapper">
  <table class="data-table" id="checkout-review-table">
    <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
    <col width="1" />
    <col width="1" />
    <?php endif; ?>
    
    <thead>
      <tr>
          <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
          <th colspan="<?php echo $colspan ?>" class="a-left"><?php echo $this->__('Price') ?></th>
          <th rowspan="<?php echo $rowspan ?>" class="a-left"><?php echo $this->__('Qty') ?></th>
          <th colspan="<?php echo $colspan ?>" class="a-left"><?php echo $this->__('Subtotal') ?></th>
      </tr>
      <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
      <tr>
          <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
          <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
          <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
          <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
      </tr>
      <?php endif; ?>
    </thead>
    
    <tbody>
      <?php foreach($this->getItems() as $_item): ?>
        <?php echo $this->getItemHtml($_item)?>
      <?php endforeach ?>
    </tbody>    
    
    <tfoot>
      <tr>
        <td colspan="3"></td>
        <td class="a-left"><?php echo $this->getChildHtml('totals');?></td>
      </tr>
      
    </tfoot>
  </table>  
  
  
  
  <div class="steps-review">
    <div class="review-item review-shipping-address">
      <p class="label"><?php echo $this->__('Shipping To');?></p>
      <?php echo $this->getShippingAddressHtml();?>
      <span class="step-edit" onclick="checkout.returnToStep('shipping');"><?php echo $this->__('edit');?></span>
    </div>
    <div class="review-item review-payment">
      <p class="label"><?php echo $this->__('Payment Method');?></p>
      <?php echo $this->getPaymentInfo();?>
      <span class="step-edit" onclick="checkout.returnToStep('payment');"><?php echo $this->__('edit');?></span>
    </div>
  </div>
    
  <div class="buttons-set" id="payment-buttons-container">
    <button type="button" class="button" title="<?php echo $this->__('Place Order') ?>" onclick="review.save();"><span><span><?php echo $this->__('Submit Order') ?></span></span></button>
  </div>
</div>
<script type="text/javascript">
//<![CDATA[
  window.review = new SimpleReview('<?php echo $this->getSaveUrl()?>');
//]]>
</script>
